In [78]:
import numpy as np
import torch
from torch import optim
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset,DataLoader

# numpy array

In [2]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])

print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
#rank, shape

print('rank of t: ', t.ndim)
print('shape of t: ', t.shape)

rank of t:  1
shape of t:  (7,)


In [4]:
#element, slicing

print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1])
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1])
print('t[:2] t[3:] = ', t[:2], t[3:])

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


In [5]:
t = np.array([[1.,2.,3.], [4.,5.,6.], [7.,8.,9.], [10.,11.,12.]])

print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [6]:
print('rank of t:', t.ndim)
print('shape of t: ', t.shape)

rank of t: 2
shape of t:  (4, 3)


# torch tensor

In [7]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [8]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0],t[1],t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [9]:
t = torch.FloatTensor([[1.,2.,3.],
                       [4.,5.,6.],
                       [7.,8.,9.],
                       [10.,11.,12.]])

print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
print(t.dim())
print(t.size())
print(t[:,1]) #1열
print(t[:,1].size())
print(t[:,:-1]) #0열,1열

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


# operation

In [11]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])

print(m1 + m2)

tensor([[5., 5.]])


In [12]:
#broadcasting

m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3])

print(m1.size())
print(m1)
print(m2.size())
print(m2)

print(m1 + m2)

torch.Size([1, 2])
tensor([[1., 2.]])
torch.Size([1])
tensor([3.])
tensor([[4., 5.]])


In [13]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])

print(m1.size())
print(m1)

print(m2.size())
print(m2)

print(m1 + m2)

torch.Size([1, 2])
tensor([[1., 2.]])
torch.Size([2, 1])
tensor([[3.],
        [4.]])
tensor([[4., 5.],
        [5., 6.]])


In [14]:
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1],[2]])

print(m1.shape)
print(m1)
print(m2.shape)
print(m2)

print(m1.matmul(m2)) #matrix product

torch.Size([2, 2])
tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 1])
tensor([[1.],
        [2.]])
tensor([[ 5.],
        [11.]])


In [16]:
#element wise product

print(m1 * m2)
print(m1.mul(m2))

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [17]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [18]:
t = torch.LongTensor([1,2])

try:

    print(t.mean())

except Exception as exc:

    print(exc)

mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long


# operation by dim

In [19]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [20]:
#mean
print(t.mean())
print(t.mean(dim = 0))
print(t.mean(dim = 1))
print(t.mean(dim = -1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [21]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [22]:
#sum

print(t.sum())
print(t.sum(dim = 0))
print(t.sum(dim = 1))
print(t.sum(dim = -1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [23]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [24]:
print(t.max())

tensor(4.)


In [25]:
#using dim, return value & index
print(t.max(dim = 0)) #max by column

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [26]:
print('max: ',t.max(dim = 0)[0])

max:  tensor([3., 4.])


In [27]:
print('argmax: ', t.max(dim = 0)[1])

argmax:  tensor([1, 1])


In [28]:
print(t.max(dim = 1)) #max by row

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [29]:
print(t.max(dim = -1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [30]:
#numpy to tensor

t = np.array([[[0,1,2],
               [3,4,5]],
              [[6,7,8],
               [9,10,11]]])

ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


#tensor manipulation

In [31]:
#view
print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [32]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [33]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [34]:
#squeeze dimension
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [35]:
ft = torch.Tensor([0,1,2])
print(ft)
print(ft.shape)

tensor([0., 1., 2.])
torch.Size([3])


In [36]:
#unsqueeze dimension
print(ft.unsqueeze(0)) #size = (3,) >>> dim = 0 >>> size = (1,3)
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [37]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [38]:
print(ft.unsqueeze(1)) #size = (3,) >>> dim = 1 >>> size =(3,1)
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [39]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [40]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [41]:
#Long to float

print(lt.float())

tensor([1., 2., 3., 4.])


In [42]:
#boolean tensor

bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [43]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


# concat & stack

In [44]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

In [45]:
print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [46]:
print(torch.cat([x,y],dim = 0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [47]:
print(torch.cat([x,y],dim = 1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [48]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [49]:
#stack은 랭크를 안늘리고 쌓아줌
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z],dim = 1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [50]:
#cat은 rank를 늘려야함
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim = 0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


# ones_like, zeros_like

In [51]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [52]:
#같은 디바이스 내에서 텐서를 선언?

print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


#원본을 변화시키는 연산

In [53]:
x = torch.FloatTensor([[1,2],[3,4]])
print(x)

tensor([[1., 2.],
        [3., 4.]])


In [54]:
print(x.mul(2.)) #원본을 변화시키지 않는다
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [55]:
print(x.mul_(2.)) #_을 쓰면 원본을 변화시킴
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


#requires_grad make parameter tensor

In [56]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])

In [57]:
#requires_grad = True는 학습할 parameter임을 명시해줌
#zeros는 0으로 초기화된 tensor

W = torch.zeros(1,requires_grad = True)
b = torch.zeros(1,requires_grad = True)

In [58]:
print(W)
print(b)

tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [60]:
#training

optimizer = optim.SGD([W,b],lr = 0.01)

epochs = 1000

for epoch in range(1,epochs+1):

    hypothesis = x_train*W + b

    cost = torch.mean((hypothesis - y_train)**2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

In [62]:
print(W)
print(b)

tensor([1.9708], requires_grad=True)
tensor([0.0664], requires_grad=True)


In [63]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[1],[2],[3]])

In [64]:
W = torch.zeros(1)
lr = 0.1

In [65]:
epochs = 10

for epoch in range(epochs+1):

    hypothesis = x_train * W

    cost = torch.mean((hypothesis - y_train)**2)
    gradient = torch.sum((W*x_train - y_train)*x_train)

    print('epoch {:4d}/{} W: {:.3f}, cost: {:.6f}'.format(
        epoch, epochs, W.item(), cost.item()
    ))

    W = W - lr * gradient

epoch    0/10 W: 0.000, cost: 4.666667
epoch    1/10 W: 1.400, cost: 0.746666
epoch    2/10 W: 0.840, cost: 0.119467
epoch    3/10 W: 1.064, cost: 0.019115
epoch    4/10 W: 0.974, cost: 0.003058
epoch    5/10 W: 1.010, cost: 0.000489
epoch    6/10 W: 0.996, cost: 0.000078
epoch    7/10 W: 1.002, cost: 0.000013
epoch    8/10 W: 0.999, cost: 0.000002
epoch    9/10 W: 1.000, cost: 0.000000
epoch   10/10 W: 1.000, cost: 0.000000


In [66]:
W = torch.zeros(1, requires_grad = True)

optimizer = optim.SGD([W], lr = 0.15)

epochs = 20

for epoch in range(epochs):

    hypothesis = x_train * W

    cost = torch.mean((hypothesis - y_train)**2)

    print('epoch {:4d}/{} W: {:.3f}, cost: {:.6f}'.format(
        epoch, epochs, W.item(), cost.item()
    ))

    #초기화
    optimizer.zero_grad()

    #미분
    cost.backward()

    #gradient descent
    optimizer.step()

epoch    0/20 W: 0.000, cost: 4.666667
epoch    1/20 W: 1.400, cost: 0.746667
epoch    2/20 W: 0.840, cost: 0.119467
epoch    3/20 W: 1.064, cost: 0.019115
epoch    4/20 W: 0.974, cost: 0.003058
epoch    5/20 W: 1.010, cost: 0.000489
epoch    6/20 W: 0.996, cost: 0.000078
epoch    7/20 W: 1.002, cost: 0.000013
epoch    8/20 W: 0.999, cost: 0.000002
epoch    9/20 W: 1.000, cost: 0.000000
epoch   10/20 W: 1.000, cost: 0.000000
epoch   11/20 W: 1.000, cost: 0.000000
epoch   12/20 W: 1.000, cost: 0.000000
epoch   13/20 W: 1.000, cost: 0.000000
epoch   14/20 W: 1.000, cost: 0.000000
epoch   15/20 W: 1.000, cost: 0.000000
epoch   16/20 W: 1.000, cost: 0.000000
epoch   17/20 W: 1.000, cost: 0.000000
epoch   18/20 W: 1.000, cost: 0.000000
epoch   19/20 W: 1.000, cost: 0.000000


In [67]:
x_train = torch.FloatTensor([[73,80,75],
                             [93,88,93],
                             [89,91,90],
                             [96,98,100],
                             [73,66,70]])

y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

In [68]:
W = torch.zeros((3,1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

In [69]:
optimizer = optim.SGD([W,b], lr = 1e-5)

In [71]:
epochs = 20

for epoch in range(epochs + 1):

    hypothesis = x_train.matmul(W) + b

    cost = torch.mean((hypothesis - y_train)**2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('epoch {:4d}/{} hypothesis: {} cost: {:.6f}'.format(
        epoch, epochs, hypothesis.squeeze().detach(), cost.item()
    ))

epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) cost: 29661.800781
epoch    1/20 hypothesis: tensor([67.2578, 80.8397, 79.6523, 86.7394, 61.6605]) cost: 9298.520508
epoch    2/20 hypothesis: tensor([104.9128, 126.0990, 124.2466, 135.3015,  96.1821]) cost: 2915.712402
epoch    3/20 hypothesis: tensor([125.9942, 151.4381, 149.2133, 162.4896, 115.5097]) cost: 915.040527
epoch    4/20 hypothesis: tensor([137.7967, 165.6247, 163.1911, 177.7112, 126.3307]) cost: 287.936096
epoch    5/20 hypothesis: tensor([144.4044, 173.5674, 171.0168, 186.2332, 132.3891]) cost: 91.371063
epoch    6/20 hypothesis: tensor([148.1035, 178.0143, 175.3980, 191.0042, 135.7812]) cost: 29.758249
epoch    7/20 hypothesis: tensor([150.1744, 180.5042, 177.8509, 193.6753, 137.6805]) cost: 10.445267
epoch    8/20 hypothesis: tensor([151.3336, 181.8983, 179.2240, 195.1707, 138.7440]) cost: 4.391237
epoch    9/20 hypothesis: tensor([151.9824, 182.6789, 179.9928, 196.0079, 139.3396]) cost: 2.493121
epoch   10/20 hypo

#torch model using nn.Module

In [73]:
class MultivariateLinearRegressionModel(nn.Module):

    def __init__(self):

        super().__init__()
        self.linear = nn.Linear(3,1)

    def forward(self, x):

        return self.linear(x)

model = MultivariateLinearRegressionModel()

optimizer = optim.SGD(model.parameters(), lr = 1e-5)

In [75]:
epochs = 20

for epoch in range(epochs + 1):

    hypothesis = model(x_train)

    cost = F.mse_loss(hypothesis, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('epoch {:4d}/{} hypothesis: {} cost: {:.6f}'.format(
        epoch, epochs, hypothesis.squeeze().detach(), cost.item()
    ))

epoch    0/20 hypothesis: tensor([31.5734, 39.8651, 38.3747, 41.0244, 31.4708]) cost: 18371.703125
epoch    1/20 hypothesis: tensor([ 84.5069, 103.4873, 101.0627, 109.2900,  79.9986]) cost: 5758.706055
epoch    2/20 hypothesis: tensor([114.1423, 139.1071, 136.1594, 147.5095, 107.1675]) cost: 1805.199829
epoch    3/20 hypothesis: tensor([130.7341, 159.0493, 155.8087, 168.9071, 122.3784]) cost: 565.985596
epoch    4/20 hypothesis: tensor([140.0232, 170.2142, 166.8096, 180.8868, 130.8945]) cost: 177.557724
epoch    5/20 hypothesis: tensor([145.2238, 176.4651, 172.9686, 187.5939, 135.6624]) cost: 55.806019
epoch    6/20 hypothesis: tensor([148.1353, 179.9648, 176.4168, 191.3489, 138.3318]) cost: 17.643421
epoch    7/20 hypothesis: tensor([149.7654, 181.9241, 178.3473, 193.4511, 139.8263]) cost: 5.681575
epoch    8/20 hypothesis: tensor([150.6779, 183.0211, 179.4281, 194.6281, 140.6631]) cost: 1.932061
epoch    9/20 hypothesis: tensor([151.1888, 183.6353, 180.0332, 195.2870, 141.1316]) cost

# torch dataset using torch.utils.data.Dataset

In [77]:
class CustomDataset(Dataset):

    def __init__(self):

        self.x_data = [[73, 80, 75],
                       [93, 88, 93],
                       [89, 91, 90],
                       [96, 98, 100],
                       [73, 66, 70]]

        self.y_data = [[152], [185], [180], [196], [142]]

    def __len__(self):

        return len(self.x_data)

    def __getitem__(self, idx):

        x = torch.FloatTensor(self.x_data[idx])
        y = torch.FloatTensor(self.y_data[idx])

        return x,y

dataset = CustomDataset()

In [79]:
dataloader = DataLoader(
    dataset,
    batch_size = 2,
    shuffle = True
)

In [80]:
epochs = 20

for epoch in range(epochs + 1):

    for batch_idx, samples in enumerate(dataloader):

        x_train, y_train  = samples

        prediction = model(x_train)

        cost = F.mse_loss(prediction, y_train)

        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        print('epoch {:4d}/{} batch {}/{} cost: {:.6f}'.format(
            epoch, epochs, batch_idx + 1, len(dataloader), cost.item()
        ))

epoch    0/20 batch 1/3 cost: 0.207312
epoch    0/20 batch 2/3 cost: 0.056680
epoch    0/20 batch 3/3 cost: 0.823586
epoch    1/20 batch 1/3 cost: 0.250032
epoch    1/20 batch 2/3 cost: 0.471759
epoch    1/20 batch 3/3 cost: 0.042345
epoch    2/20 batch 1/3 cost: 0.180257
epoch    2/20 batch 2/3 cost: 0.582011
epoch    2/20 batch 3/3 cost: 0.073183
epoch    3/20 batch 1/3 cost: 0.184993
epoch    3/20 batch 2/3 cost: 0.412829
epoch    3/20 batch 3/3 cost: 0.122024
epoch    4/20 batch 1/3 cost: 0.498531
epoch    4/20 batch 2/3 cost: 0.063394
epoch    4/20 batch 3/3 cost: 0.036055
epoch    5/20 batch 1/3 cost: 0.022809
epoch    5/20 batch 2/3 cost: 0.223392
epoch    5/20 batch 3/3 cost: 0.967673
epoch    6/20 batch 1/3 cost: 0.252709
epoch    6/20 batch 2/3 cost: 0.442125
epoch    6/20 batch 3/3 cost: 0.039095
epoch    7/20 batch 1/3 cost: 0.153871
epoch    7/20 batch 2/3 cost: 0.509555
epoch    7/20 batch 3/3 cost: 0.010296
epoch    8/20 batch 1/3 cost: 0.054676
epoch    8/20 batch 2/3 c

# set seed to reproducibility

In [81]:
torch.manual_seed(1)

In [82]:
x_data = [[1,2], [2,3], [3,1], [4,3], [5,3], [6,2]]
y_data = [[0], [0], [0], [1], [1], [1]]

In [83]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [84]:
print(x_train.shape)
print(x_train)

torch.Size([6, 2])
tensor([[1., 2.],
        [2., 3.],
        [3., 1.],
        [4., 3.],
        [5., 3.],
        [6., 2.]])


In [85]:
print(y_train.shape)
print(y_train)

torch.Size([6, 1])
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])


In [86]:
W = torch.zeros((2,1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

In [87]:
#naive hypothesis
hypothesis = 1/(1+torch.exp(-(x_train.matmul(W)+b)))

print(hypothesis)
print(hypothesis.shape)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<MulBackward0>)
torch.Size([6, 1])


In [88]:
#use sigmoid function

hypothesis = torch.sigmoid(x_train.matmul(W)+b)

print(hypothesis)
print(hypothesis.shape)

tensor([[0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000],
        [0.5000]], grad_fn=<SigmoidBackward0>)
torch.Size([6, 1])


In [89]:
#naive cross entropy

losses = -(y_train*torch.log(hypothesis) + (1 - y_train)*torch.log(1 - hypothesis))

print(losses)

tensor([[0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931],
        [0.6931]], grad_fn=<NegBackward0>)


In [90]:
cost = losses.mean()
print(cost)

tensor(0.6931, grad_fn=<MeanBackward0>)


In [91]:
#use cross entropy function

F.binary_cross_entropy(hypothesis, y_train)

tensor(0.6931, grad_fn=<BinaryCrossEntropyBackward0>)

In [92]:
W = torch.zeros((2,1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

optimizer = optim.SGD([W,b], lr = 1)

In [93]:
#training

epochs = 1000
for epoch in range(epochs + 1):

    hypothesis = torch.sigmoid(x_train.matmul(W) + b)
    cost = F.binary_cross_entropy(hypothesis, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:

        print('epoch {:4d}/{} cost: {:.6f}'.format(
            epoch, epochs, cost.item()
        ))

epoch    0/1000 cost: 0.693147
epoch  100/1000 cost: 0.134722
epoch  200/1000 cost: 0.080643
epoch  300/1000 cost: 0.057900
epoch  400/1000 cost: 0.045300
epoch  500/1000 cost: 0.037261
epoch  600/1000 cost: 0.031672
epoch  700/1000 cost: 0.027556
epoch  800/1000 cost: 0.024394
epoch  900/1000 cost: 0.021888
epoch 1000/1000 cost: 0.019852


In [94]:
hypothesis = torch.sigmoid(x_train.matmul(W) + b)
print(hypothesis[:5])

tensor([[2.7648e-04],
        [3.1608e-02],
        [3.8977e-02],
        [9.5622e-01],
        [9.9823e-01]], grad_fn=<SliceBackward0>)


In [95]:
prediction = hypothesis >= torch.FloatTensor([0.5])
print(prediction[:5])

tensor([[False],
        [False],
        [False],
        [ True],
        [ True]])


In [96]:
print(y_train[:5])

tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.]])


In [97]:
correct_prediction = prediction.float() == y_train
print(correct_prediction)

tensor([[True],
        [True],
        [True],
        [True],
        [True],
        [True]])


# binary classifier training using linear sigmoid

In [98]:
class BinaryClassifier(nn.Module):

    def __init__(self):

        super().__init__()
        self.linear = nn.Linear(2,1) #크기 조절 가능
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):

        return self.sigmoid(self.linear(x))

In [99]:
model = BinaryClassifier()

In [100]:
optimizer = optim.SGD(model.parameters(), lr = 1)

In [102]:
epochs = 100

for epoch in range(epochs + 1):

    hypothesis = model(x_train)

    cost = F.binary_cross_entropy(hypothesis, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 10 == 0:

        prediction = hypothesis >= torch.FloatTensor([0.5])

        correct_prediction = prediction.float() == y_train

        accuracy = correct_prediction.sum().item()/len(correct_prediction)

        print('epoch {:4d}/{} cost: {:.6f} accuracy {:2.2f}%'.format(
            epoch, epochs, cost.item(), accuracy*100
        ))

epoch    0/100 cost: 0.527002 accuracy 83.33%
epoch   10/100 cost: 0.994596 accuracy 66.67%
epoch   20/100 cost: 0.570399 accuracy 83.33%
epoch   30/100 cost: 0.473909 accuracy 83.33%
epoch   40/100 cost: 0.388606 accuracy 83.33%
epoch   50/100 cost: 0.307901 accuracy 83.33%
epoch   60/100 cost: 0.235923 accuracy 83.33%
epoch   70/100 cost: 0.182916 accuracy 100.00%
epoch   80/100 cost: 0.155795 accuracy 100.00%
epoch   90/100 cost: 0.143031 accuracy 100.00%
epoch  100/100 cost: 0.133369 accuracy 100.00%


# softmax function

In [103]:
z = torch.FloatTensor([1,2,3])

hypothesis = F.softmax(z, dim = 0)

print(hypothesis)

tensor([0.0900, 0.2447, 0.6652])


In [104]:
hypothesis.sum()

tensor(1.)

In [107]:
z = torch.rand(3,5, requires_grad = True)

print(z)

hypothesis = F.softmax(z, dim = 1)

print(hypothesis)

tensor([[0.1980, 0.4162, 0.2843, 0.3398, 0.5239],
        [0.7981, 0.7718, 0.0112, 0.8100, 0.6397],
        [0.9743, 0.8300, 0.0444, 0.0246, 0.2588]], requires_grad=True)
tensor([[0.1703, 0.2118, 0.1857, 0.1963, 0.2359],
        [0.2328, 0.2268, 0.1060, 0.2356, 0.1987],
        [0.3189, 0.2760, 0.1258, 0.1234, 0.1559]], grad_fn=<SoftmaxBackward0>)


In [106]:
y = torch.randint(5,(3,)).long()
print(y)

tensor([2, 1, 0])


In [108]:
y_one_hot = torch.zeros_like(hypothesis)

y_one_hot.scatter_(1, y.unsqueeze(1), 1)

tensor([[0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.]])

In [109]:
cost = (y_one_hot * -torch.log(hypothesis)).sum(dim = 1).mean()
print(cost)

tensor(1.4368, grad_fn=<MeanBackward0>)


In [110]:
F.log_softmax(z, dim = 1)

tensor([[-1.7701, -1.5519, -1.6838, -1.6284, -1.4442],
        [-1.4574, -1.4837, -2.2442, -1.4455, -1.6158],
        [-1.1430, -1.2872, -2.0728, -2.0927, -1.8584]],
       grad_fn=<LogSoftmaxBackward0>)

In [111]:
#https://pytorch.org/docs/stable/generated/torch.nn.functional.nll_loss.html
#https://velog.io/@skyhelper/CrossEntorpyLoss-NLLLoss-%EB%AC%B4%EC%97%87%EC%9D%B4-%EB%8B%A4%EB%A5%B8%EA%B0%80
F.nll_loss(F.log_softmax(z, dim = 1),y)

tensor(1.4368, grad_fn=<NllLossBackward0>)

In [112]:
F.cross_entropy(z,y)

tensor(1.4368, grad_fn=<NllLossBackward0>)

In [113]:
x_train = [[1,2,1,1],
           [2,1,3,2],
           [3,1,3,4],
           [4,1,5,5],
           [1,7,5,5],
           [1,2,5,6],
           [1,6,6,6],
           [1,7,7,7]]

y_train = [2,2,2,1,1,1,0,0]

x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)

In [114]:
W = torch.zeros([4,3], requires_grad = True)
b = torch.zeros(1, requires_grad = True)

In [115]:
optimizer = optim.SGD([W,b], lr = 0.1)

In [116]:
#naive cross entropy

epochs = 1000

for epoch in range(epochs + 1):

    hypothesis = F.softmax(x_train.matmul(W) + b, dim = 1)

    y_one_hot = torch.zeros_like(hypothesis)
    y_one_hot.scatter_(1, y_train.unsqueeze(1), 1)

    cost = (y_one_hot* -torch.log(F.softmax(hypothesis, dim = 1))).sum(dim = 1).mean()

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:

        print('epoch {:4d}/{} cost: {:.6f}'.format(
            epoch, epochs, cost.item()
        ))

epoch    0/1000 cost: 1.098612
epoch  100/1000 cost: 0.901535
epoch  200/1000 cost: 0.839114
epoch  300/1000 cost: 0.807826
epoch  400/1000 cost: 0.788472
epoch  500/1000 cost: 0.774822
epoch  600/1000 cost: 0.764449
epoch  700/1000 cost: 0.756191
epoch  800/1000 cost: 0.749398
epoch  900/1000 cost: 0.743671
epoch 1000/1000 cost: 0.738749


In [117]:
W = torch.zeros((4,3), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

In [118]:
optimizer = optim.SGD([W,b], lr = 0.1)

In [119]:
#torch cross entropy

epochs = 1000
for epoch in range(epochs + 1):

    z = x_train.matmul(W) + b
    cost = F.cross_entropy(z, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:

        print('epoch {:4d}/{} cost:{:.6f}'.format(
            epoch, epochs, cost.item()
        ))

epoch    0/1000 cost:1.098612
epoch  100/1000 cost:0.761050
epoch  200/1000 cost:0.689991
epoch  300/1000 cost:0.643229
epoch  400/1000 cost:0.604117
epoch  500/1000 cost:0.568256
epoch  600/1000 cost:0.533922
epoch  700/1000 cost:0.500291
epoch  800/1000 cost:0.466908
epoch  900/1000 cost:0.433507
epoch 1000/1000 cost:0.399962


In [120]:
class SoftmaxClassifierModel(nn.Module):

    def __init__(self):

        super().__init__()
        self.linear = nn.Linear(4,3)

    def forward(self, x):

        return self.linear(x)

model = SoftmaxClassifierModel()

In [121]:
optimizer = optim.SGD(model.parameters(), lr = 0.1)

In [122]:
epochs = 1000
for epoch in range(epochs + 1):

    prediction = model(x_train)

    cost = F.cross_entropy(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:

        print('epoch {:4d}/{} cost:{:.6f}'.format(
            epoch, epochs, cost.item()
        ))

epoch    0/1000 cost:1.777960
epoch  100/1000 cost:0.654127
epoch  200/1000 cost:0.561501
epoch  300/1000 cost:0.505037
epoch  400/1000 cost:0.460010
epoch  500/1000 cost:0.420253
epoch  600/1000 cost:0.383131
epoch  700/1000 cost:0.347032
epoch  800/1000 cost:0.310780
epoch  900/1000 cost:0.274060
epoch 1000/1000 cost:0.244281


#train & test

In [123]:
x_train = torch.FloatTensor([[1,2,1],
                             [1,3,2],
                             [1,3,4],
                             [1,5,5],
                             [1,7,5],
                             [1,2,5],
                             [1,6,6],
                             [1,7,7]])

#이게 long tensor여야 한다??
y_train = torch.LongTensor([2,2,2,1,1,1,0,0])

In [124]:
x_test = torch.FloatTensor([[2,1,1],[3,1,2], [3,3,4]])
y_test = torch.LongTensor([2,2,2])

In [125]:
class SoftmaxClassifierModel(nn.Module):

    def __init__(self):

        super().__init__()
        self.linear = nn.Linear(3,3)

    def forward(self, x):

        return self.linear(x)

model = SoftmaxClassifierModel()

In [126]:
optimizer = optim.SGD(model.parameters(), lr = 0.1)

In [127]:
def train(model, optimizer, x_train, y_train):

    epochs = 20

    for epoch in range(epochs):

        prediction = model(x_train)

        cost = F.cross_entropy(prediction, y_train)

        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        print('epoch {:4d}/{} cost: {:.6f}'.format(
            epoch, epochs, cost.item()
        ))

In [128]:
def test(model, optimizer, x_test, y_test):

    prediction = model(x_test)

    predicted_classes = prediction.max(1)[1]

    correct_count = (predicted_classes == y_test).sum().item()

    cost = F.cross_entropy(prediction, y_test)

    print('accuracy: {} % cost: {:.6f}'.format(
        correct_count/len(y_test)*100, cost.item()
    ))

In [129]:
train(model, optimizer, x_train, y_train)

epoch    0/20 cost: 1.628863
epoch    1/20 cost: 1.113791
epoch    2/20 cost: 1.077432
epoch    3/20 cost: 1.065552
epoch    4/20 cost: 1.055705
epoch    5/20 cost: 1.046451
epoch    6/20 cost: 1.037633
epoch    7/20 cost: 1.029140
epoch    8/20 cost: 1.020929
epoch    9/20 cost: 1.012959
epoch   10/20 cost: 1.005209
epoch   11/20 cost: 0.997662
epoch   12/20 cost: 0.990306
epoch   13/20 cost: 0.983131
epoch   14/20 cost: 0.976129
epoch   15/20 cost: 0.969294
epoch   16/20 cost: 0.962621
epoch   17/20 cost: 0.956103
epoch   18/20 cost: 0.949736
epoch   19/20 cost: 0.943515


In [130]:
test(model, optimizer, x_test, y_test)

accuracy: 0.0 % cost: 1.673393


In [131]:
model = SoftmaxClassifierModel()
optimizer = optim.SGD(model.parameters(), lr = 1e5)

In [132]:
train(model, optimizer, x_train, y_train)

epoch    0/20 cost: 1.997079
epoch    1/20 cost: 951884.000000
epoch    2/20 cost: 2179194.750000
epoch    3/20 cost: 515946.468750
epoch    4/20 cost: 1365132.250000
epoch    5/20 cost: 1513232.000000
epoch    6/20 cost: 1205009.000000
epoch    7/20 cost: 1487007.250000
epoch    8/20 cost: 769071.437500
epoch    9/20 cost: 1030419.562500
epoch   10/20 cost: 1608882.250000
epoch   11/20 cost: 1458134.000000
epoch   12/20 cost: 794819.750000
epoch   13/20 cost: 1053115.625000
epoch   14/20 cost: 1263232.000000
epoch   15/20 cost: 885444.812500
epoch   16/20 cost: 1869071.500000
epoch   17/20 cost: 181076.343750
epoch   18/20 cost: 1018740.625000
epoch   19/20 cost: 969481.937500


In [133]:
model = SoftmaxClassifierModel()
optimizer = optim.SGD(model.parameters(), lr = 1e-10)

In [134]:
train(model, optimizer, x_train,y_train)

epoch    0/20 cost: 2.766672
epoch    1/20 cost: 2.766672
epoch    2/20 cost: 2.766672
epoch    3/20 cost: 2.766672
epoch    4/20 cost: 2.766672
epoch    5/20 cost: 2.766672
epoch    6/20 cost: 2.766672
epoch    7/20 cost: 2.766672
epoch    8/20 cost: 2.766672
epoch    9/20 cost: 2.766672
epoch   10/20 cost: 2.766672
epoch   11/20 cost: 2.766672
epoch   12/20 cost: 2.766672
epoch   13/20 cost: 2.766672
epoch   14/20 cost: 2.766672
epoch   15/20 cost: 2.766672
epoch   16/20 cost: 2.766672
epoch   17/20 cost: 2.766672
epoch   18/20 cost: 2.766672
epoch   19/20 cost: 2.766672


# normalization

In [135]:
x_train = torch.FloatTensor([[73,80,75],
                             [93,88,93],
                             [89,91,90],
                             [96,98,100],
                             [73,66,70]])

y_train = torch.FloatTensor([[152],[185],[180],[196],[142]])

In [136]:
mu = x_train.mean(dim = 0)

print(mu)

tensor([84.8000, 84.6000, 85.6000])


In [138]:
sigma = x_train.std(dim = 0)
print(sigma)

tensor([11.0544, 12.2393, 12.6214])


In [139]:
norm_x_train = (x_train - mu)/sigma

In [140]:
print(norm_x_train)

tensor([[-1.0674, -0.3758, -0.8398],
        [ 0.7418,  0.2778,  0.5863],
        [ 0.3799,  0.5229,  0.3486],
        [ 1.0132,  1.0948,  1.1409],
        [-1.0674, -1.5197, -1.2360]])


In [142]:
class MultivariateLinearRegressionModel(nn.Module):

    def __init__(self):

        super().__init__()
        self.linear = nn.Linear(3,1)

    def forward(self,x):

        return self.linear(x)

In [143]:
model = MultivariateLinearRegressionModel()

optimizer = optim.SGD(model.parameters(), lr = 1e-1)

In [144]:
def train(model, optimizer, x_train, y_train):

    epochs = 20

    for epoch in range(epochs):

        prediction = model(x_train)

        cost = F.mse_loss(prediction, y_train)

        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        print('epoch {:4d}/{} cost: {:.6f}'.format(
            epoch, epochs, cost.item()
        ))

In [145]:
train(model, optimizer, norm_x_train, y_train)

epoch    0/20 cost: 29574.599609
epoch    1/20 cost: 18789.699219
epoch    2/20 cost: 11985.388672
epoch    3/20 cost: 7659.157715
epoch    4/20 cost: 4898.668945
epoch    5/20 cost: 3134.367676
epoch    6/20 cost: 2005.911133
epoch    7/20 cost: 1283.897583
epoch    8/20 cost: 821.862427
epoch    9/20 cost: 526.171387
epoch   10/20 cost: 336.928650
epoch   11/20 cost: 215.809128
epoch   12/20 cost: 138.288208
epoch   13/20 cost: 88.669762
epoch   14/20 cost: 56.909168
epoch   15/20 cost: 36.577866
epoch   16/20 cost: 23.561457
epoch   17/20 cost: 15.226631
epoch   18/20 cost: 9.888277
epoch   19/20 cost: 6.467782


In [146]:
train(model, optimizer, x_train, y_train)

epoch    0/20 cost: 3990187.250000
epoch    1/20 cost: 77254491111424.000000
epoch    2/20 cost: 1495896652666455982080.000000
epoch    3/20 cost: 28965388040134986626616000512.000000
epoch    4/20 cost: 560863570271672329540262620787900416.000000
epoch    5/20 cost: inf
epoch    6/20 cost: inf
epoch    7/20 cost: inf
epoch    8/20 cost: inf
epoch    9/20 cost: inf
epoch   10/20 cost: inf
epoch   11/20 cost: inf
epoch   12/20 cost: nan
epoch   13/20 cost: nan
epoch   14/20 cost: nan
epoch   15/20 cost: nan
epoch   16/20 cost: nan
epoch   17/20 cost: nan
epoch   18/20 cost: nan
epoch   19/20 cost: nan
