# create tensor

numpy array를 받아서, torch.FloatTensor()로 float tensor로 바꿔줌

In [1]:
#numpy array 생성

import numpy as np

n_array = np.arange(10).reshape(2,5)
n_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [2]:
#tensor 생성

import torch #보통 별칭을 사용하지 않음

tensor = torch.FloatTensor(n_array)
tensor

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

# size()

tensor의 shape를 나타냄

In [4]:
n_array.size #numpy에서는 데이터의 수

10

In [5]:
tensor.size() #pytorch에서는 shape

torch.Size([2, 5])

In [6]:
n_array.shape

(2, 5)

In [7]:
tensor.shape #pytorch에서 shape도 가능

torch.Size([2, 5])

# dim

numpy의 axis연산이 pytorch에서는 dim으로 이루어짐

In [8]:
n1 = np.arange(10).reshape(5,2)
n1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
t1 = torch.FloatTensor(n1)
t1

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])

In [10]:
#각 열별 평균
t1.mean(dim=0)

tensor([4., 5.])

In [11]:
#각 행별 평균
t1.mean(dim=1)

tensor([0.5000, 2.5000, 4.5000, 6.5000, 8.5000])

# view

numpy의 reshape 연산은 array의 shape를 바꿔주는데.. pytorch에서는 view가 이 역할을 함

In [13]:
n1 = np.arange(10)
n1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
t1 = torch.FloatTensor(n1)
t1

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [20]:
t1.size()

torch.Size([10])

In [15]:
#1번째 차원을 2로 하고..
#0번째 차원을 -1로 함
#-1로 하면, 적당한 값을 자동으로 잡아줌.

#a * 2 = 10이 되어야 하니, -1에는 5가 들어감

t1.view(-1,2)

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])

# squeeze, unsqueeze

squeeze()는 rank를 줄이고, unsqueeze()는 rank를 늘려줌

In [21]:
t1

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [28]:
t1.shape

torch.Size([10])

unsqueeze시키면, 차원이 늘어남

In [27]:
t1.unsqueeze(dim=0)

tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [30]:
t1.unsqueeze(dim=0).shape

torch.Size([1, 10])

In [25]:
t1.unsqueeze(dim=1)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [31]:
t1.unsqueeze(dim=1).shape

torch.Size([10, 1])

unsqueeze된 tensor를 squeeze하면, 차원이 감소

In [32]:
t1.unsqueeze(dim=1).squeeze()

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [33]:
t1.unsqueeze(dim=0).squeeze()

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# auto differentiation

자동 미분을 지원함

$z=2w^{2}+5$를 w로 미분하고, f'(2)를 구함

In [34]:
#w에 대한 다른 변수의 미분을 구할려면, requires_grad=True로 해줘야함
w = torch.tensor(2.0,requires_grad=True)

y = w**2

z = 2*y + 5

In [35]:
#z를 w로 미분함

z.backward()

In [36]:
w.grad

tensor(8.)