# 1. numpy로 tensor 만들기

1-1) 1차원 텐서

In [1]:
import numpy as np

In [2]:
#list를 생성해 np.array로 1차원 array로 변환
t = np.array([0.,1.,2.,3.,4.,5.,6.])

print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
#차원과 크기

print("Rank of t:", t.ndim)
print("Shape of t:", t.shape)

Rank of t: 1
Shape of t: (7,)


1-2) 원소 접근(인덱싱)

In [4]:
print('t[0] t[1], t[-1] = ', t[0], t[1], t[-1]) #인덱스를 통한 원소 접근

t[0] t[1], t[-1] =  0.0 1.0 6.0


1-3) 슬라이싱

In [5]:
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1]) #[시작번호: 끝번호]로 범위 지정

t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]


In [6]:
print('t[:2] t[:3]    = ' , t[:2], t[3:]) #시작 번호 생략, 끝 번호 생략

t[:2] t[:3]    =  [0. 1.] [3. 4. 5. 6.]


1-4) 2차원 tensor

In [7]:
t = np.array([[1.,2.,3.], [4.,5.,6.], [7.,8.,9.], [10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [8]:
print('Rank of t: ', t.ndim)
print('Shape of t:', t.shape)

Rank of t:  2
Shape of t: (4, 3)


# 2. pytorch로 tensor 만들기

In [9]:
import torch

2-1) 1차원 tensor

In [10]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [11]:
#dim은 rank(차원)

#shape, size()는 tensor의 크기

print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([7])
torch.Size([7])


In [12]:
#인덱싱과 슬라이싱 가능

print(t[0],t[1],t[-1]) #인덱싱
print(t[2:5], t[4:-1]) #슬라이싱
print(t[:2], t[3:]) #슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


2-2) 2차원 tensor

In [13]:
t = torch.FloatTensor([[1.,2.,3.], 
                       [4.,5.,6.],
                       [7.,8.,9.],
                       [10.,11.,12.]
                       ])

print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [14]:
#dim()으로 차원, size()로 shape(크기)

print(t.dim()) #rank
print(t.size()) #shape

2
torch.Size([4, 3])


In [15]:
#슬라이싱 가능
print(t[:,1]) #첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다
print(t[:,1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [16]:
print(t[:,:-1]) #첫번째 차원을 전체 선택한 상황에서, 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져온다

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


# 3. broadcasting

3-1) 같은 크기일때

In [17]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])

print(m1+m2)

tensor([[5., 5.]])


3-2) 크기가 다를때

In [18]:
#vector + scalar

m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3]) #[3] -> [3,3]

print(m1+m2)

tensor([[4., 5.]])


3-3) vector간 broadcasting

In [19]:
#2*1 vector + 1*2 vector

m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])
print(m1+m2)

"""
[1, 2]
==> [[1, 2],
     [1, 2]]
[3]
[4]
==> [[3, 3],
     [4, 4]]
"""

tensor([[4., 5.],
        [5., 6.]])


'\n[1, 2]\n==> [[1, 2],\n     [1, 2]]\n[3]\n[4]\n==> [[3, 3],\n     [4, 4]]\n'

# 4. 자주 사용되는 기능

4-1) 행렬 곱셈(matmul)

In [20]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])

print('Shape of Matrix1: ', m1.shape) #2*2
print('Shape of Matrix2: ', m2.shape) #2*1

print(m1.matmul(m2)) #2*1


Shape of Matrix1:  torch.Size([2, 2])
Shape of Matrix2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


4-2) elementwise product

In [21]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])

print('Shape of Matrix 1: ', m1.shape) #2*2
print('Shape of Matrix 2: ', m2.shape) #2*1

print(m1 * m2) #2*2
print(m1.mul(m2))

"""
# 브로드캐스팅 과정에서 m2 텐서가 어떻게 변경되는지 보겠습니다.
[1]
[2]
==> [[1, 1],
     [2, 2]]
"""

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


'\n# 브로드캐스팅 과정에서 m2 텐서가 어떻게 변경되는지 보겠습니다.\n[1]\n[2]\n==> [[1, 1],\n     [2, 2]]\n'

4-3) 평균

In [22]:
#1차원
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [23]:
#2차원
t = torch.FloatTensor([[1,2],[3,4]])
print(t)
print(t.mean())

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)


In [24]:
#차원을 인자로
#열방향 평균
print(t.mean(dim=0))

"""
# 실제 연산 과정
t.mean(dim=0)은 입력에서 첫번째 차원을 제거한다.

[[1., 2.],
 [3., 4.]]

1과 3의 평균을 구하고, 2와 4의 평균을 구한다.
결과 ==> [2., 3.]
"""

tensor([2., 3.])


'\n# 실제 연산 과정\nt.mean(dim=0)은 입력에서 첫번째 차원을 제거한다.\n\n[[1., 2.],\n [3., 4.]]\n\n1과 3의 평균을 구하고, 2와 4의 평균을 구한다.\n결과 ==> [2., 3.]\n'

In [25]:
#행방향 평균

print(t.mean(dim=1))

tensor([1.5000, 3.5000])


In [26]:
#dim = -1

#마지막 차원인 열을 제거
#즉, 행방향으로 평균

print(t.mean(dim = -1))

tensor([1.5000, 3.5000])


4-4) 덧셈

In [27]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [28]:
print(t.sum()) #단순히 원소 전체의 덧셈을 수행
print(t.sum(dim = 0)) #행을 제거
print(t.sum(dim = 1)) #열을 제거
print(t.sum(dim = -1)) #열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


4-5) max와 argmax

In [29]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [30]:
#.max()는 원소들의 최댓값
print(t.max())

tensor(4.)


In [31]:
#dim연산 가능

print(t.max(dim = 0))

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [32]:
#인덱싱으로 max와 argmax를 가져온다

print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [33]:
#argmax

print(t.argmax(dim=0))

tensor([1, 1])


In [34]:
print(t.max(dim = 1))
print(t.max(dim = -1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


# 5. 심화 기능

5-1) view

In [35]:
t = np.array([[[0,1,2],
               [3,4,5]],
              [[6,7,8],
               [9,10,11]]])

ft = torch.FloatTensor(t)

In [36]:
print(ft.shape)

torch.Size([2, 2, 3])


In [37]:
print(ft.view([-1,3])) #ft라는 텐서를 (?,3)의 크기로 변경

print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [38]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


5-2) squeeze

In [39]:
ft = torch.FloatTensor([[0],[1],[2]])

print(ft)

print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [40]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


5-3) unsqueeze

In [41]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [42]:
print(ft.unsqueeze(0)) #인덱스 0은 첫번째 차원을 의미
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [43]:
#view를 이용해 unsqueeze를 구현할 수 있다

print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [44]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [45]:
#-1은 인덱스로 마지막 위치를 나타내므로, 마지막 차원에 1을 추가

print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


# 6. type casting

In [46]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [47]:
#.float()하면 float tensor로 변경

print(lt.float())

tensor([1., 2., 3., 4.])


In [48]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [49]:
#.long()하면 long 타입의 tensor가 되고
#.float()하면 float 타입의 tensor가 된다

print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


# 7. concatenate

In [50]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])

In [52]:
print(x)

tensor([[1., 2.],
        [3., 4.]])


In [53]:
print(y)

tensor([[5., 6.],
        [7., 8.]])


In [51]:
#dim = 0은 첫번째 차원을 기준으로 연결

print(torch.cat([x,y],dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [54]:
#dim = 1은 두번째 차원을 기준으로 연결

print(torch.cat([x,y],dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


# 8. stacking

In [55]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

print(x)
print(y)
print(z)

tensor([1., 4.])
tensor([2., 5.])
tensor([3., 6.])


In [56]:
#torch.stack()을 이용해 3개의 벡터를 stacking

print(torch.stack([x,y,z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [57]:
#stacking은 cat에 unsqueeze를 동시에 써야 구현가능하다

print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim = 0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [58]:
#dim = 1을 주면 두번째 차원을 기준으로 stacking해준다

print(torch.stack([x,y,z],dim = 1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


# 9. ones_like, zeros_like

In [59]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])

print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [60]:
#ones_like는 동일한 크기를 가지면서 모든 원소를 1로 채운다

print(torch.ones_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [61]:
#zeros_like를 하면 동일한 크기이면서 모든 원소를 0으로 채운다

print(torch.zeros_like(x))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


# 10. in-place

In [62]:
x = torch.FloatTensor([[1,2],[3,4]])
print(x)

tensor([[1., 2.],
        [3., 4.]])


In [63]:
#x의 각 원소에 2를 곱한 결과와 x를 출력

print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [64]:
#연산 뒤에 _을 붙이면 기존 x에 덮어쓰기 해준다

print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
