**Lab 1-2 : Graph Representation**
- 본 실습에서는 그래프를 표현할 수 있는 다양한 방법에 대해서 알아본다.


In [2]:
import networkx as nx
import os
import numpy as np
import sys

np.set_printoptions(threshold = sys.maxsize)

In [7]:
G = nx.Graph() #무방향 그래프

In [8]:
# 10개의 node로 이루어진, 원 모양의 그래프 정보를 가져옵니다.
# 각 데이터셋은 edge 형태로 저장되어 있습니다.
print("###### Read Graphs ######")

f = [[1,2],[2,3],[3,4],[4,5],[5,6],[6,7],[7,8],[8,9],[9,10],[10,1]]

for edge in f:

    v1,v2 = edge
    G.add_edge(v1,v2)

print(G.edges)

###### Read Graphs ######
[(1, 2), (1, 10), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9), (9, 10)]


In [9]:
#그래프를 인접 리스트로 저장

print("###### Graph to List #######")
ListGraph = nx.to_dict_of_lists(G)

for v in ListGraph:

    print(str(v) + " : " + str(ListGraph[v]))

###### Graph to List #######
1 : [2, 10]
2 : [1, 3]
3 : [2, 4]
4 : [3, 5]
5 : [4, 6]
6 : [5, 7]
7 : [6, 8]
8 : [7, 9]
9 : [8, 10]
10 : [9, 1]


In [10]:
#그래프를 간선 리스트로 저장
print("###### Graph to EdgeList ######")

EdgeListGraph = nx.to_edgelist(G)

for e in EdgeListGraph:

    v1,v2,w = e
    print(v1,v2)

###### Graph to EdgeList ######
1 2
1 10
2 3
3 4
4 5
5 6
6 7
7 8
8 9
9 10


In [11]:
#그래프를 인접 행렬(일반 행렬)로 저장

print("###### Graph to numpy array ######")

NumpyArrayGraph = nx.to_numpy_array(G)

print(NumpyArrayGraph)

###### Graph to numpy array ######
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [12]:
#그래프를 인접행렬(희소 행렬)로 저장

print("###### Graph to Scipy sparse array ######")

SparseMatrixGraph = nx.to_scipy_sparse_array(G)

print(SparseMatrixGraph)

###### Graph to Scipy sparse array ######
  (0, 1)	1
  (0, 9)	1
  (1, 0)	1
  (1, 2)	1
  (2, 1)	1
  (2, 3)	1
  (3, 2)	1
  (3, 4)	1
  (4, 3)	1
  (4, 5)	1
  (5, 4)	1
  (5, 6)	1
  (6, 5)	1
  (6, 7)	1
  (7, 6)	1
  (7, 8)	1
  (8, 7)	1
  (8, 9)	1
  (9, 0)	1
  (9, 8)	1
